### ISSUE TITLE
Translation to Sindarin does not work

### ISSUE THREAD

**Issue by CyberPotat42** [Animenosekai/translate#49]
An error occurs in the Yandex Translate module when trying to translate text into Sindarin:
```python
from translatepy.translators.yandex import YandexTranslate
from translatepy import Language
translate = YandexTranslate()
translate.translate("Hello World", "Sindarin")
```
gives an error:
```console
Traceback (most recent call last):
  File "d:\Projects\translatepy\translate\translatepy\test_sjn.py", line 4, in <module>
    translate.translate("Hello World", "sjn")
  File "C:\Users\Potato\AppData\Roaming\Python\Python39\site-packages\translatepy\translators\base.py", line 93, in translate
    dest_code = self._detect_and_validate_lang(destination_language)
  File "C:\Users\Potato\AppData\Roaming\Python\Python39\site-packages\translatepy\translators\base.py", line 560, in _detect_and_validate_lang
    raise UnsupportedLanguage("The language {language_code} is not supported 
by {service}".format(language_code=language, service=str(self)))
translatepy.exceptions.UnsupportedLanguage: The language Sindarin is not supported by Yandex
```
Although Yandex is perfectly able to translate into Sindarin: [see here](https://translate.yandex.ru/?lang=en-sjn&text=Hello%20World)

**Comment by CyberPotat42** [comment]
This simple code can show that the Yandex Translate API responds to such requests:
```python
api_url = "https://translate.yandex.net/api/v1/tr.json/translate"
params = {"ucid": str(uuid.uuid4()).replace("-", ""), "srv": "android", "format": "text"}
data = {"text": "Hello World", "lang": "ru-sjn"}
request = session.post(api_url, params=params, data=data)
response = request.json()
print(response["text"][0])
```
Prints: `tlE xr^5{#5$ x7E4` and that's right
