### ISSUE TITLE
[SERVER]: cannot import name 'General' from 'nasse.config' 

### ISSUE THREAD

**Issue by ZhymabekRoman** [Animenosekai/translate#85]
```bash
@ZhymabekRoman ➜ /workspaces/translate (cli-dev-1) $ translatepy server
Traceback (most recent call last):
  File "/home/codespace/.python/current/bin/translatepy", line 8, in <module>
    sys.exit(main())
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/translatepy/__main__.py", line 166, in main
    raise err
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/translatepy/__main__.py", line 153, in main
    from translatepy.server import translation
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/translatepy/server/translation.py", line 11, in <module>
    from translatepy.server.server import app
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/translatepy/server/server.py", line 2, in <module>
    from nasse.config import General
ImportError: cannot import name 'General' from 'nasse.config' (/usr/local/python/3.10.8/lib/python3.10/site-packages/nasse/config.py)
```

**Comment by Animenosekai** [comment]
Yea sorry I'm making lots of changes to Nasse right now which I'm going to release maybe tomorrow so it should work great then (and I need to update the server).

Current in my priority queue, `nasse` will be released soon as I mostly finished the v2, some minor projects will be made public but they won't take long and `translatepy` will be my main focus.

I'm sorry but I've been very busy this year and couldn't really focus on anything. I'm trying to make up for the delay rn.
